= Wraith Systems Operator Manual
Doc Writer <doc@example.com>
v0.0.0, 2022-04-25
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right
:toclevels: 3
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

[quote,Me]
____
How the heck do I make this work?
____

TIP:  This manual contains several sections.
The <<Internals>> section explains the mechanics of the server.
<<Installation>> details specific steps for building, installing, and configuring the application.

The Wraith Systems Operator Manual is copyright &copy; 2022 by Michael D Henderson.
All rights reserved.

:sectnums:
== Introduction
*_Wraith_* is a game unlike any other that I have published in the past.

NOTE:  This is a NOTE.

=== Components
The *_Wraith Server_* (also called "the game engine" or just "the engine")
is a single executable.

== Internals
You don't need this information to be a good person.

=== Environment

=== Security

==== Role Based Access Control

1. authorized
2. admin
3. sysop
4. gameop
5. player


== Installation
This section describes the steps for building, installing, and configuring the application.

=== System Requirements
You must have Git installed.

You must have Go version 1.18 or newer.

You should have a proxy like Nginx between the engine and the Internet.

=== Fetch
Use Git to clone the repository.

=== Compile
Run `go build` in the repository directory.

This manual assumes that you will move the `wraith` executable into your PATH.
If you do not, you must specify the path as part of the command line.
For example,

    $ ~/src/wraith/wraith version

=== Initialize
The `wraith init` command creates a configuration file containing:

1. Secrets
2. Default Accounts
3. Default Paths

    $ wraith init \
      --config ~/.wraith.json \
      --hash-secret 'fooofoooofooo' \
      --admin-secret 'boooboooobooo' \
      --sysop-secret 'baaabaaaabaaa'

=== Start Server
After you have created the configuration file, start the server:

    $ wraith server --config ~/.wraith.json

The configuration file defaults to `~/.wraith.json` on Linux systems, so you can start the server with:

    $ wraith server

=== Linux

=== MacOS

=== Windows


== Configuration
To make configuration changes,
you may edit the configuration file or use the API.

=== Creating Games

=== Adding Accounts

== Datastore Management

== CORS and Proxy Management

[appendix]
== Commands
This section details the command line options for the application.

The examples in this section assume a Bash shell.

=== Init
The `wraith init` command creates a minimal configuration file for the application.
The configuration data includes the location of the datastore,
secrets for the `sysop` account and signing tokens.

=== Server
The `wraith server` command starts the API server.
It loads the global configuration file before loading the datastores containing the current game data.

=== Version
The `wraith version` shows the version of the application.

Usage:

    $ wraith version

[appendix]
== Role Based Access Control
The API uses the following roles to control access to functionality.

[glossary]
admin:: This role is assigned to all users that have administrative rights on the game data.
authorized:: This role is assigned to all users that have successfully logged in to the server.
gameop:: This role is assigned to users that have administrative rights to a specific game.
player:: This role is assigned to all users that are playing in a specific game.
sysop:: This role is assigned only to the `sysop` account.

[index]
== Index