////////////////////////////////////////////////////////////////////////////////
// wraith - the wraith game engine and server
// Copyright (c) 2022 Michael D. Henderson
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
////////////////////////////////////////////////////////////////////////////////

package words

// defaultWordList returns a list generated from the English TV and Movie list from
// https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists.
func defaultWordList() []string {
	// wget https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/TV/2006/1-1000
	// mv 1-1000 0001-1000
	// wget https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/TV/2006/1001-2000
	// wget https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/TV/2006/2001-3000
	// grep -h '^<td' 0001-1000 1001-2000 2001-3000 |
	//   grep /wiki/ |
	//   sed -e 's/.*title="//' -e 's/".*//' |
	//   awk 'length($0) > 3 {print}'| tr '[A-Z]' '[a-z]' |
	//   sort -u -o tvwords.txt
	// vi tvwords.txt  ## removed words with punctuation, etc
	// sort -u -o tvwords.txt |
	//   awk '{printf("\"%s\",", $0); if (NR % 10 == 0) {printf("\n");}}'

	return []string{
		"aaron", "abbott", "abby", "abigail", "able", "about", "above", "absolutely", "accept", "accepted",
		"access", "accident", "according", "account", "accused", "across", "acting", "action", "actually", "adam",
		"address", "admit", "admitted", "adult", "advantage", "advice", "affair", "afford", "afraid", "after",
		"afternoon", "again", "against", "agency", "agent", "agree", "agreed", "agreement", "ahead", "ahem",
		"aidan", "airport", "alan", "alarm", "alcazar", "alex", "alexandra", "alexis", "alien", "alison",
		"alive", "allison", "allow", "allowed", "almost", "alone", "along", "already", "alright", "also",
		"although", "always", "amanda", "amazing", "amber", "ambulance", "america", "american", "among", "amount",
		"ancient", "andy", "angel", "anger", "angry", "animal", "animals", "anna", "anniversary", "another",
		"answer", "answered", "answering", "answers", "antonio", "anybody", "anymore", "anyone", "anything", "anytime",
		"anyway", "anywhere", "apart", "apartment", "apologize", "apology", "apparently", "appear", "appointment", "appreciate",
		"area", "argue", "argument", "arms", "army", "around", "arrest", "arrested", "arrived", "article",
		"artist", "ashamed", "ashley", "aside", "asked", "asking", "asleep", "asshole", "assignment", "assistant",
		"assume", "assumed", "assuming", "assure", "attack", "attacked", "attention", "attitude", "attorney", "attractive",
		"audience", "audrey", "aunt", "austin", "available", "avoid", "awake", "aware", "away", "awesome",
		"awful", "awfully", "awhile", "awkward", "babe", "babies", "baby", "back", "badly", "bags",
		"bail", "baldwin", "ball", "balls", "band", "bank", "barbara", "barely", "barry", "bars",
		"bart", "base", "baseball", "based", "basement", "basically", "bath", "bathroom", "battle", "beach",
		"bear", "beat", "beating", "beautiful", "beauty", "became", "because", "become", "becoming", "bedroom",
		"been", "beer", "before", "begging", "begin", "beginning", "behavior", "behind", "being", "believe",
		"believed", "believes", "bell", "belle", "belong", "belongs", "benefit", "besides", "best", "beth",
		"betrayed", "better", "between", "beyond", "bianca", "bigger", "biggest", "bike", "bill", "billy",
		"bird", "birth", "birthday", "bite", "black", "blah", "blair", "blake", "blame", "bleeding",
		"bless", "blew", "blind", "block", "blonde", "blood", "bloody", "blow", "blue", "board",
		"boat", "bobby", "bodies", "body", "bomb", "bond", "bone", "bones", "bonnie", "book",
		"books", "bored", "boring", "born", "borrow", "boss", "boston", "both", "bother", "bothering",
		"bottle", "bottom", "bought", "bout", "bowl", "boyfriend", "boys", "brad", "brady", "brain",
		"brains", "brand", "brandon", "brave", "bread", "break", "breakfast", "breaking", "breaks", "breath",
		"breathe", "breathing", "brenda", "brian", "bride", "bridge", "bridget", "bright", "brilliant", "bring",
		"bringing", "brings", "brittany", "broke", "broken", "brooke", "brother", "brothers", "brought", "brown",
		"bryant", "buchanan", "bucks", "buddy", "buffy", "build", "building", "built", "bull", "bullet",
		"bunch", "buried", "burn", "burned", "burning", "burns", "business", "bust", "busted",
		"busy", "butt", "button", "buying", "cabin", "cake", "caleb", "california", "call", "called",
		"calling", "calls", "calm", "came", "camera", "camp", "campaign", "cancel", "cancer", "candy",
		"cannot", "capable", "captain", "card", "cards", "care", "cared", "career", "careful", "cares",
		"carl", "carly", "carmen", "caroline", "carry", "carrying", "cars", "carter", "cartman", "case",
		"cases", "casey", "cash", "cassie", "cast", "catch", "caught", "cause", "caused", "celebrate",
		"cell", "center", "century", "ceremony", "certain", "certainly", "chad", "chair", "challenge", "champagne",
		"chance", "chances", "chandler", "change", "changed", "changes", "changing", "character", "charge", "charges",
		"charity", "charles", "charlie", "charming", "chase", "chasing", "chat", "cheap", "cheating", "check",
		"checked", "checking", "cheer", "cheese", "chef", "chest", "chicago", "chick", "chicken", "chief",
		"child", "children", "chill", "chinese", "chip", "chloe", "chocolate", "choice", "choices", "choose",
		"chose", "chris", "christ", "christine", "christmas", "church", "circumstances", "city", "claim", "claire",
		"class", "classes", "clean", "cleaning", "clear", "clearly", "clever", "client", "clinic", "clock",
		"close", "closed", "closer", "closet", "closing", "clothes", "club", "clue", "coach", "coast",
		"coat", "code", "coffee", "coincidence", "colby", "cold", "cole", "colin", "colleen", "college",
		"colonel", "color", "coma", "come", "comes", "comfort", "comfortable", "comin", "coming", "command",
		"commit", "commitment", "committed", "common", "community", "company", "competition", "complete", "completely", "complicated",
		"computer", "concentrate", "concern", "concerned", "condition", "conference", "confess", "confession", "confidence", "confused",
		"congratulations", "connected", "connection", "conscience", "consider", "considered", "considering", "contact", "continue", "contract",
		"control", "conversation", "convince", "convinced", "cook", "cookies", "cooking", "cool", "cops", "copy",
		"corinthos", "corner", "correct", "cost", "couch", "could", "count", "counting", "country", "couple",
		"course", "court", "courtney", "cousin", "cover", "covered", "covering", "crack", "craig", "crane",
		"crap", "crash", "crazy", "cream", "create", "created", "credit", "crew", "crime", "criminal",
		"crisis", "cristian", "cross", "crossed", "crowd", "cruel", "crush", "crying", "cure", "curious",
		"curse", "custody", "cute", "cutting", "daddy", "damage", "dance", "dancing", "danger", "dangerous",
		"daniel", "danny", "daphne", "dare", "daria", "dark", "darling", "date", "dates", "dating",
		"daughter", "dave", "david", "dawn", "dawson", "days", "deacon", "dead", "deal", "dealing",
		"dean", "dear", "death", "decent", "decide", "decided", "decision", "decisions", "deep", "defend",
		"defense", "definitely", "degree", "delicious", "deliver", "delivery", "demon", "demons", "deny", "department",
		"depends", "deserve", "deserves", "desire", "desk", "desperate", "despite", "dessert", "destiny", "destroy",
		"destroyed", "detail", "details", "detective", "determined", "devil", "diamond", "diana", "diane", "died",
		"diego", "dies", "difference", "different", "difficult", "dinner", "direct", "direction", "director", "dirt",
		"dirty", "disappear", "disappeared", "disappointed", "disaster", "discovered", "discuss", "discussion", "disease", "disgusting",
		"distance", "district", "divorce", "divorced", "dixie", "doctor", "doctors", "does", "dogs", "doin",
		"doing", "doll", "dollar", "dollars", "done", "donna", "door", "doors", "double", "doubt",
		"down", "downstairs", "dozen", "drag", "draw", "dream", "dreamed", "dreaming", "dreams", "dress",
		"dressed", "drink", "drinking", "drinks", "drive", "driver", "driving", "drop", "dropped", "dropping",
		"drove", "drug", "drugs", "drunk", "dude", "dumb", "dump", "dumped", "during", "dust",
		"duty", "dying", "each", "earlier", "early", "ears", "earth", "easier", "easily", "east",
		"easy", "eating", "eddie", "edge", "edmund", "edward", "effect", "eggs", "eight", "either",
		"elaine", "elevator", "eleven", "elizabeth", "else", "embarrassed", "embarrassing", "emergency", "emily", "emotional",
		"empty", "ended", "ending", "ends", "enemy", "energy", "engaged", "engagement", "english", "enjoy",
		"enjoying", "enough", "entire", "entirely", "eric", "erica", "escape", "escaped", "especially", "estate",
		"ethan", "europe", "even", "evening", "event", "eventually", "ever", "every", "everybody", "everyone",
		"everything", "everywhere", "evidence", "evil", "exact", "exactly", "example", "excellent", "except", "exchange",
		"excited", "exciting", "excuse", "exist", "expect", "expected", "expecting", "expensive", "experience", "expert",
		"explain", "explanation", "extra", "extremely", "eyes", "fabulous", "face", "faces", "fact", "facts",
		"fail", "failed", "fair", "faith", "fake", "fall", "falling", "falls", "false", "familiar",
		"families", "family", "famous", "fancy", "fantastic", "fantasy", "farm", "fashion", "fast", "faster",
		"fate", "father", "fault", "favor", "favorite", "fear", "federal", "feed", "feel", "feeling",
		"feelings", "feels", "feet", "fell", "fellow", "felt", "female", "fever", "field", "fifteen",
		"fifth", "fifty", "fight", "fighting", "figure", "figured", "file", "files", "fill", "filled",
		"film", "final", "finally", "find", "finding", "finds", "fine", "finger", "fingers", "finish",
		"finished", "fire", "fired", "firm", "first", "fish", "fishing", "five", "fixed", "flash",
		"flat", "flesh", "flight", "floor", "flowers", "flying", "focus", "folks", "follow", "followed",
		"following", "food", "fool", "foot", "football", "force", "forced", "forever", "forget", "forgive",
		"forgot", "forgotten", "form", "former", "forrester", "fortune", "forty", "forward", "fought", "found",
		"four", "fourth", "frank", "frankie", "frankly", "fraser", "frasier", "freak", "freaked", "fred",
		"free", "freedom", "freeze", "french", "fresh", "friday", "friend", "friendly", "friends", "friendship",
		"from", "front", "full", "fully", "funeral", "funny", "further", "future", "game", "games",
		"gang", "garage", "garbage", "garden", "gate", "gave", "general", "generous", "genius", "gentleman",
		"gentlemen", "george", "gets", "gettin", "getting", "ghost", "giant", "gift", "gifts", "giles",
		"gimme", "girl", "girlfriend", "girls", "give", "given", "gives", "giving", "glad", "glass",
		"glasses", "glen", "goddamn", "goes", "goin", "going", "gold", "gone", "gonna", "good",
		"goodbye", "goodness", "goodnight", "gorgeous", "gosh", "gotta", "gotten", "government", "grab", "grace",
		"grade", "grand", "grandfather", "grandma", "grandmother", "grandpa", "grant", "grateful", "grave", "great",
		"greatest", "green", "greenlee", "greta", "grew", "grief", "ground", "group", "grow", "growing",
		"grown", "guarantee", "guard", "guards", "guess", "guest", "guests", "guilt", "guilty", "guns",
		"guts", "guys", "gwen", "hair", "half", "hall", "halloween", "hand", "handed", "handle",
		"handled", "hands", "handsome", "hang", "hanging", "hank", "happen", "happened", "happening", "happens",
		"happier", "happiness", "happy", "hard", "harder", "hardly", "harley", "harm", "harmony", "harold",
		"harry", "harvard", "harvey", "hate", "hated", "hates", "have", "having", "hayward", "head",
		"headed", "heading", "heads", "health", "healthy", "hear", "heard", "hearing", "heart", "hearts",
		"heat", "heaven", "heavy", "heck", "held", "helen", "helena", "hell", "hello", "help",
		"helped", "helping", "helps", "henry", "here", "hero", "hers", "herself", "hidden", "hide",
		"hiding", "high", "higher", "highly", "hilda", "hill", "himself", "hire", "hired", "history",
		"hits", "hitting", "hold", "holden", "holding", "hole", "holiday", "hollywood", "holy", "home",
		"homer", "homework", "honest", "honestly", "honey", "honeymoon", "honor", "hook", "hope", "hopefully",
		"hopes", "hoping", "horrible", "horse", "hospital", "hotel", "hour", "hours", "house", "however",
		"huge", "human", "humor", "hundred", "hung", "hungry", "hunt", "hurry", "hurt", "hurting",
		"hurts", "husband", "idea", "ideas", "idiot", "ignore", "illegal", "image", "imagine", "immediately",
		"important", "impossible", "impressed", "impression", "including", "incredible", "incredibly", "indeed", "information", "innocent",
		"insane", "inside", "insist", "instead", "insurance", "intend", "interest", "interested", "interesting", "interrupt",
		"interview", "into", "introduce", "investigation", "invitation", "invite", "invited", "involved", "isaac", "isabella",
		"island", "issue", "issues", "itself", "jack", "jacket", "jackie", "jackson", "jail", "jake",
		"jamal", "james", "jamie", "jane", "jason", "jealous", "jeez", "jennifer", "jenny", "jerk",
		"jerry", "jess", "jessica", "jesus", "jill", "jimmy", "jobs", "joey", "john", "johnny",
		"join", "joint", "joke", "joking", "josh", "judge", "judgment", "juice", "julia", "julian",
		"jump", "jumped", "junior", "jury", "just", "justice", "kane", "karen", "kate", "katie",
		"keep", "keeping", "keeps", "kelly", "kendall", "kenny", "kept", "keri", "kevin", "keys",
		"kick", "kicked", "kidding", "kidnapped", "kids", "kill", "killed", "killer", "killing", "kills",
		"kind", "kinda", "kinds", "king", "kiss", "kissed", "kissing", "kitchen", "knees", "knew",
		"knife", "knock", "knocked", "know", "knowing", "knowledge", "known", "knows", "kramer", "kristina",
		"kyle", "ladies", "lady", "laid", "lake", "lame", "land", "lane", "language", "large",
		"larry", "last", "late", "lately", "later", "latest", "laugh", "laughing", "laundry", "laura",
		"laurence", "laurie", "lawyer", "lawyers", "lead", "leader", "leads", "league", "learn", "learned",
		"learning", "least", "leave", "leaves", "leaving", "left", "legal", "legs", "less", "lesson",
		"lets", "letter", "letters", "letting", "level", "lewis", "lexie", "liar", "library", "license",
		"lied", "lies", "lieutenant", "life", "lifetime", "lift", "light", "lights", "like", "liked",
		"likely", "likes", "lily", "lindsay", "line", "lines", "lips", "lisa", "list", "listen",
		"listened", "listening", "little", "live", "lived", "lives", "living", "liza", "lizzie", "load",
		"local", "lock", "locked", "locker", "logan", "london", "lonely", "long", "longer", "look",
		"looked", "looking", "looks", "loose", "lord", "lorelai", "lose", "loser", "losing", "loss",
		"lost", "lots", "loud", "lousy", "love", "loved", "lovely", "lover", "loves", "loving",
		"lower", "lucas", "luck", "lucky", "lucy", "luis", "luke", "lunch", "lying", "machine",
		"mackenzie", "made", "magazine", "maggie", "magic", "maid", "mail", "main", "major", "make",
		"makes", "making", "malcolm", "male", "mall", "mama", "manage", "managed", "manager", "manning",
		"mansion", "many", "marah", "margaret", "margo", "maria", "maris", "mark", "market", "marriage",
		"married", "marry", "marrying", "marshall", "martin", "marty", "mary", "master", "match", "mate",
		"mateo", "material", "math", "matt", "matter", "matters", "matthew", "maureen", "maybe", "mayor",
		"meal", "mean", "meaning", "means", "meant", "meantime", "meat", "medical", "medication", "medicine",
		"meet", "meeting", "member", "members", "memories", "memory", "mental", "mention", "mentioned", "merry",
		"mess", "message", "messages", "messed", "mexico", "michael", "michelle", "middle", "midnight", "might",
		"miguel", "mike", "mile", "miles", "military", "milk", "million", "millions", "mimi", "mind",
		"minds", "mine", "minute", "minutes", "miracle", "mirror", "miserable", "miss", "missed", "missing",
		"mission", "mistake", "mistakes", "mister", "mitch", "mixed", "model", "molly", "moment", "moments",
		"mommy", "monday", "money", "monica", "monkey", "monster", "montgomery", "month", "months", "mood",
		"moon", "more", "morgan", "morning", "most", "mostly", "mother", "mountain", "mouth", "move",
		"moved", "moves", "movie", "movies", "moving", "much", "murder", "murdered", "murderer", "music",
		"must", "myself", "mystery", "nail", "naked", "name", "named", "names", "nancy", "nasty",
		"natalie", "nate", "national", "natural", "nature", "nbsp", "near", "nearly", "necessary", "neck",
		"need", "needed", "needs", "negative", "neighborhood", "neil", "neither", "nerve", "nervous", "never",
		"newman", "news", "newspaper", "next", "nice", "nicholas", "nick", "nicole", "night", "nightmare",
		"nights", "nikki", "nikolas", "niles", "nine", "nobody", "noise", "none", "nope", "nora",
		"normal", "north", "nose", "note", "notes", "nothin", "nothing", "notice", "noticed", "nowhere",
		"number", "numbers", "nurse", "nuts", "oakdale", "obvious", "obviously", "ocean", "odds", "offense",
		"offer", "offered", "offering", "office", "officer", "official", "officially", "often", "okay", "older",
		"olivia", "once", "ones", "only", "onto", "open", "opened", "opening", "operation", "opinion",
		"opportunity", "option", "options", "orange", "order", "ordered", "orders", "original", "other", "others",
		"otherwise", "ought", "ours", "ourselves", "outfit", "outside", "outta", "over", "pack", "package",
		"packed", "page", "paid", "paige", "pain", "painful", "paint", "painting", "pair", "palmer",
		"panic", "pants", "paper", "papers", "pardon", "parent", "parents", "paris", "park", "parker",
		"parking", "part", "particular", "parties", "partner", "parts", "party", "pass", "passed", "passing",
		"passion", "past", "path", "pathetic", "patient", "patients", "paul", "paying", "peace", "penny",
		"people", "percent", "perfect", "perfectly", "perhaps", "period", "permission", "person", "personal", "personally",
		"pete", "peter", "phil", "philip", "phillip", "phoebe", "phone", "photo", "phyllis", "physical",
		"pick", "picked", "picking", "picture", "pictures", "piece", "pieces", "pilar", "pills", "pilot",
		"pine", "pink", "piper", "pissed", "pity", "pizza", "place", "places", "plan", "plane",
		"planet", "planned", "planning", "plans", "plant", "plate", "play", "played", "player", "playing",
		"please", "pleased", "pleasure", "plenty", "plus", "pocket", "point", "points", "poison", "police",
		"policy", "pool", "poor", "popular", "port", "position", "positive", "possibility", "possible", "possibly",
		"post", "potential", "pounds", "power", "powerful", "powers", "practically", "practice", "pray", "precious",
		"prefer", "pregnancy", "pregnant", "prepare", "prepared", "present", "presents", "president", "press", "pressure",
		"pretend", "pretending", "pretty", "price", "pride", "prince", "princess", "prison", "prisoner", "privacy",
		"private", "prize", "probably", "problem", "problems", "procedure", "process", "professional", "professor", "program",
		"progress", "project", "prom", "promise", "promised", "proof", "proper", "property", "protect", "protecting",
		"protection", "proteus", "proud", "prove", "prue", "psycho", "public", "pull", "pulled", "pulling",
		"punch", "pure", "purpose", "purse", "push", "pushed", "pushing", "puts", "putting", "quality",
		"quarter", "queen", "question", "questions", "quick", "quickly", "quiet", "quinn", "quit", "quite",
		"race", "rachel", "radar", "radio", "rafe", "rain", "raise", "raised", "randy", "rare",
		"rate", "rather", "raul", "reach", "reached", "reaction", "read", "reading", "ready", "real",
		"reality", "realize", "realized", "really", "reason", "reasonable", "reasons", "rebecca", "recall", "recently",
		"recognize", "record", "records", "refuse", "regret", "regular", "relationship", "relax", "release", "released",
		"remain", "remember", "remembered", "remind", "reminds", "rent", "repeat", "report", "reputation", "request",
		"rescue", "research", "respect", "responsibility", "responsible", "rest", "restaurant", "results", "return", "revenge",
		"rich", "richard", "rick", "ricky", "ride", "ridge", "ridiculous", "riding", "right", "rights",
		"ring", "rise", "risk", "river", "road", "robert", "rock", "roger", "role", "roll",
		"rolling", "romance", "romantic", "roof", "room", "rooms", "rory", "rosanna", "rose", "ross",
		"rough", "round", "routine", "rude", "ruin", "ruined", "rule", "rules", "running", "runs",
		"rush", "russell", "ryan", "sabrina", "safe", "safety", "said", "sake", "salad", "sale",
		"salem", "sally", "same", "sami", "sandwich", "santa", "santos", "sarah", "saturday", "save",
		"saved", "saving", "saying", "says", "scare", "scared", "scary", "scene", "schedule", "school",
		"science", "score", "scott", "scream", "screaming", "screen", "screw", "screwed", "sean", "search",
		"season", "seat", "seats", "seattle", "second", "seconds", "secret", "secretary", "secrets", "section",
		"secure", "security", "seeing", "seem", "seemed", "seems", "seen", "sees", "self", "selfish",
		"sell", "selling", "senator", "send", "sending", "senior", "sense", "sensitive", "sent", "sentence",
		"separate", "serious", "seriously", "serve", "served", "service", "seth", "setting", "settle", "settled",
		"seven", "several", "sexual", "sexy", "shake", "shall", "shame", "shape", "share", "shared",
		"sharing", "sharon", "sharp", "shawn", "sheridan", "sheriff", "shift", "ship", "shirt",
		"shock", "shoe", "shoes", "shoot", "shooting", "shop", "shopping", "short", "shot", "shots",
		"should", "shoulder", "show", "showed", "shower", "showing", "shows", "shut", "sick", "side",
		"sight", "sign", "signal", "signed", "signs", "silent", "silly", "silver", "simon", "simone",
		"simple", "simply", "since", "sing", "singing", "single", "sister", "sisters", "site", "sitting",
		"situation", "sixty", "size", "skin", "skip", "skye", "slayer", "sleep", "sleeping", "slept",
		"slip", "slow", "small", "smart", "smell", "smells", "smile", "smiling", "smith", "smoke",
		"smoking", "snake", "sneak", "snow", "snyder", "social", "society", "soda", "soft", "sold",
		"solid", "solution", "solve", "some", "somebody", "someday", "somehow", "someone", "someplace", "something",
		"sometime", "sometimes", "somewhere", "song", "sonny", "soon", "sooner", "sorry", "sort", "soul",
		"sound", "sounded", "sounds", "soup", "source", "south", "space", "spare", "spaulding", "speak",
		"speaking", "special", "specific", "speech", "speed", "spell", "spend", "spending", "spent", "spike",
		"spirit", "spit", "split", "spoke", "spoken", "sports", "spot", "spread", "spring", "square",
		"staff", "stage", "stairs", "stake", "stamp", "stan", "stand", "standing", "stands", "star",
		"staring", "starr", "stars", "start", "started", "starting", "starts", "state", "statement", "states",
		"station", "stay", "stayed", "staying", "stays", "steal", "stealing", "step", "stephanie", "stephen",
		"steps", "steve", "stick", "sticking", "still", "stock", "stole", "stolen", "stomach", "stone",
		"stood", "stop", "stopped", "stopping", "store", "stories", "storm", "story", "straight", "strange",
		"stranger", "street", "streets", "strength", "stress", "strike", "strong", "stronger", "stuck", "student",
		"students", "study", "studying", "stuff", "stupid", "style", "subject", "success", "successful", "such",
		"sudden", "suddenly", "suffer", "suffering", "sugar", "suggest", "suggesting", "suicide", "suit", "suite",
		"summer", "sunday", "super", "support", "suppose", "supposed", "sure", "surely", "surgery", "surprise",
		"surprised", "survive", "susan", "suspect", "suspicious", "swear", "sweat", "sweater", "sweet", "sweetheart",
		"sweetie", "swim", "swing", "switch", "sydney", "system", "tabitha", "table", "tail", "take",
		"taken", "takes", "taking", "talent", "talk", "talked", "talkin", "talking", "talks", "tall",
		"tape", "target", "taste", "taught", "taylor", "teach", "teacher", "team", "tear", "tears",
		"teeth", "television", "tell", "telling", "tells", "term", "terms", "terrible", "terribly", "terrific",
		"tess", "test", "testify", "tests", "than", "thank", "thanks", "thanksgiving", "that", "their",
		"them", "themselves", "then", "theory", "therapy", "there", "theresa", "these", "they", "thin",
		"thing", "things", "think", "thinking", "thinks", "third", "thirty", "this", "thomas", "those",
		"though", "thought", "thoughts", "thousand", "threat", "threatened", "threatening", "three", "threw", "thrilled",
		"throat", "through", "throw", "throwing", "thrown", "thursday", "ticket", "tickets", "tied", "tight",
		"till", "time", "times", "timing", "timmy", "tiny", "tired", "toast", "toby", "today",
		"todd", "together", "toilet", "told", "tommy", "tomorrow", "tongue", "tonight", "tony", "took",
		"tory", "total", "totally", "touch", "touched", "tough", "tour", "toward", "towards", "town",
		"track", "trade", "traffic", "train", "training", "trap", "trapped", "trash", "travel", "travers",
		"treat", "treated", "treating", "treatment", "tree", "trey", "trial", "trick", "tricks", "tried",
		"tries", "trip", "trouble", "troy", "truck", "true", "truly", "trust", "trusted", "truth",
		"trying", "turkey", "turn", "turned", "turning", "turns", "twelve", "twenty", "twice", "twins",
		"type", "ugly", "unbelievable", "uncle", "uncomfortable", "under", "understand", "understanding", "understood", "unfortunately",
		"union", "unit", "united", "universe", "university", "unless", "until", "unusual", "upon", "upset",
		"upstairs", "used", "using", "usual", "usually", "vacation", "valley", "value", "vampire", "vampires",
		"vanessa", "vegas", "very", "victim", "victor", "victoria", "video", "view", "viki", "vision",
		"visit", "voice", "vote", "vulnerable", "wait", "waited", "waiting", "wake", "walk", "walked",
		"walking", "walks", "wall", "wallet", "walls", "walter", "wanna", "want", "wanted", "wanting",
		"wants", "warm", "warn", "warned", "warning", "warrant", "wash", "washington", "waste", "wasting",
		"watch", "watched", "watching", "water", "ways", "weak", "weapon", "weapons", "wear", "wearing",
		"weather", "wedding", "week", "weekend", "weeks", "weight", "weird", "welcome", "well", "went",
		"were", "wesley", "west", "what", "whatever", "wheel", "when", "whenever", "where", "wherever",
		"whether", "which", "while", "whip", "white", "whitney", "who", "whoa", "whoever", "whole",
		"whom", "whose", "wide", "wife", "wild", "will", "william", "willing", "willow", "wind",
		"window", "wine", "wings", "winner", "winning", "winter", "wise", "wish", "witch", "witches",
		"with", "within", "without", "witness", "woke", "wolf", "woman", "women", "wonder", "wonderful",
		"wondering", "wood", "woods", "word", "words", "wore", "work", "worked", "working", "works",
		"world", "worried", "worry", "worrying", "worse", "worst", "worth", "would", "wound", "write",
		"writing", "written", "wrong", "wrote", "xander", "yeah", "year", "years", "yell", "yelling",
		"yellow", "yesterday", "york", "young", "younger", "your", "yours", "yourself", "yourselves", "zack",
		"zander", "zelda", "zero",
	}
}
